### ISSUE TITLE
[BUG] Latest Releases performance issues

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#138]
**Describe the bug**
Depending on the date span, retrieving and rendering the latest releases can take a long time.

**To Reproduce**
Extend latest releases data range to 365 days

**Additional context**
Restrict latest releases date span to 30 days and default date picker to last 7 days.

**Comment by damienderoistecso** [comment]
@JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
Test passed. Only last 30 days available

**Comment by damienderoistecso** [comment]
If I pick today's date and there were no releases today, I get an error from server.

```
2020-05-28 16:25:35,927 [56] ERROR PxStat.Template.BaseTemplate_Read`2.Read:100 - System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at PxStat.Data.Cube_BSO.ExecuteReadCollection(ADO theAdo, Cube_DTO_ReadCollection DTO) in C:\Wspace\2.3.0\server\PxStat\Entities\Data\Cube\BSO\Cube_BSO.cs:line 82
   at PxStat.Data.Cube_BSO_ReadCollection.Execute() in C:\Wspace\2.3.0\server\PxStat\Entities\Data\Cube\BSO\Cube_BSO_ReadCollection.cs:line 60
   at PxStat.Template.BaseTemplate_Read`2.Read() in C:\Wspace\2.3.0\server\PxStat\Entities\Template\BaseTemplate_Read.cs:line 100
2020-05-28 16:25:35,942 [56] INFO API.ADO.Dispose:614 - SQL Server Connection disposed
2020-05-28 16:25:35,942 [56] INFO API.JSONRPC.ParseError:242 - IP: 3.15.13.190, Error Code: -32099, Error Message: Application error, Error Data: An unexpected error has occurred. Please seek technical support.

```

**Comment by neilfromcork** [comment]
@damienderoistecso - fix in place for previous issue, ready for test

**Comment by damienderoistecso** [comment]
@neilfromcork No results returns null. Can an empty array be returned instead?

**Comment by neilfromcork** [comment]
@damienderoistecso - Updated. No results returning an empty json object now.

**Comment by neilfromcork** [comment]
@damienderoistecso - or, more correctly, a json object with an empty array!

**Comment by damienderoistecso** [comment]
Fixed and tested

**Comment by lorenzobruni** [comment]
SERVER SIDE ERRROR:
```
2020-06-01 12:51:58,969 [36] ERROR PxStat.Template.BaseTemplate_Read`2.Read:100 - Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot convert null to 'System.DateTime' because it is a non-nullable value type
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at PxStat.Data.Cube_BSO.ExecuteReadCollection(ADO theAdo, Cube_DTO_ReadCollection DTO) in Z:\Workbench\PxStat\trunk\server\PxStat\Entities\Data\Cube\BSO\Cube_BSO.cs:line 87
   at PxStat.Data.Cube_BSO_ReadCollection.Execute() in Z:\Workbench\PxStat\trunk\server\PxStat\Entities\Data\Cube\BSO\Cube_BSO_ReadCollection.cs:line 57
   at PxStat.Template.BaseTemplate_Read`2.Read() in Z:\Workbench\PxStat\trunk\server\PxStat\Entities\Template\BaseTemplate_Read.cs:line 100
```

CLIENT SIDE ERROR: API out of synch
![image](https://user-images.githubusercontent.com/53212047/83407224-2d9a4500-a408-11ea-8487-cf658197fe14.png)

Please look at this with top priority as it's blocking the release. Thanks.

**Comment by neilfromcork** [comment]
Fixed -ready for test @lorenzobruni @damienderoistecso

**Comment by damienderoistecso** [comment]
Client side error resolved. Drawing API params in datatable draw callback
Latest Releases performance issues #138

**Comment by damienderoistecso** [comment]
@JohnPCarroll ready for test

**Comment by JohnPCarroll** [comment]
Test passed. Used today's date and no error occurred
