### ISSUE TITLE
[BUG] Emails failing when it finds no email in AD for user

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#418]
**Describe the bug**
"PxStat.System.Notification.Email_API.GroupMessageCreate" failing when it finds a user with no email as a results of being deleted from AD.

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at PxStat.System.Notification.Email_BSO_GroupMessage_Create.Execute() in Z:\Workbench\PxStat\trunk\server\PxStat\Entities\System\Notification\Email\BSO\Email_BSO_GroupMessage_Create.cs:line 67
   at PxStat.Template.BaseTemplate_Read`2.Read() in Z:\Workbench\PxStat\trunk\server\PxStat\Entities\Template\BaseTemplate_Read.cs:line 121
```

**Comment by liamie** [comment]
Tested with my email in a group with a removed AD user.
I received email correctly. Seems to be now bypassing user with no email as required.
