### ISSUE TITLE
[BUG] Build Create inconsistent between Live and Dev

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#651]
**Describe the bug**
Build Create inconsistent between Live and Dev

**To Reproduce**

1. Go to Build Create 
2. Click on Import 
3. Import source file for matrix B0504
4.  Build dimensions and click create > px at bottom
5. In live  new px file is produced in Dev See error

**Expected behavior**
Consistent between live and dev

**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/193014176-4c378c66-8e39-4568-8342-74e3223f3514.png)

**Comment by damiancosmoschapman** [comment]
This is the log file entry  for the above error:

2022-09-29 12:13:17,623 [37] ERROR PxStat.Template.BaseTemplate_Read`2.Read:208 - System.AggregateException: One or more errors occurred. ---> System.DivideByZeroException: Attempted to divide by zero.
   at PxStat.DataStore.DataReader.GetQualifyingOrdinals(IStatDimension dim, Int32 mcount) in C:\Wspace\5.2\server\PxStat\Entities\Data\DataStore\DataReader.cs:line 399
   at PxStat.DataStore.DataReader.<>c__DisplayClass13_0.<RunFractalQueryOrdinalsOnly>b__0(StatDimension dim) in C:\Wspace\5.2\server\PxStat\Entities\Data\DataStore\DataReader.cs:line 284

**Comment by liamie** [comment]
Strangely a precision line seems to be added to this B0504 in dev create and  update even though there is non in the original source.

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for  test

**Comment by liamie** [comment]
Seems cleared now.
